### ISSUE TITLE
Quets:  Frost Nova Blood Elf Mage 

### ISSUE THREAD

**Issue by iliarakov** [HellscreamWoW/Tracker#3660] opened 2015-11-19 06:49 UTC
http://www.wowhead.com/quest=10068/frost-nova
quest  Frost Nova  for blood elf mage I don't working  because I go in Training Dummy  but when I use frost nova noting is don't happened

**Comment by GMTyrial** [comment] 2015-12-10 19:32
Duplicate of https://github.com/HellscreamWoW/Tracker/issues/887

**Closed by GMTyrial** 2015-12-10 19:32 UTC
Labels: Class-Mage, Type-Quest, Type-Script
