### ISSUE TITLE
 Guild Master NPC in IronForge/Tabard Crest Issues

### ISSUE THREAD

**Issue by DelphineGnome** [HellscreamWoW/Tracker#581] opened 2015-05-23 18:01 UTC
Having a problem with creating/changing guild crest for my guild. I created a crest originally, the NPC took money but gave me a completely crest to what i had chosen for our guild tabards.

Tried to change it a number of times, he either changes it to a random design or doesnt do anything at all but still takes the 10g each time. 

Kindly address when possible.

Thanks

**Comment by Reloque** [comment] 2015-05-24 08:32
#505

**Comment by EPS1L0N** [comment] 2015-05-25 01:34
duplicate of #505

**Closed by EPS1L0N** 2015-05-25 01:34 UTC
Labels: Priority-High, Type-Creature
