### ISSUE TITLE
zone :northern barrens/quest :Through Fire and Flames

### ISSUE THREAD

**Issue by Max-Hellscream** [HellscreamWoW/Tracker#317] opened 2015-05-22 05:02 UTC
"when u use item to release trapted wolfs nothing hapening
http://www.wowhead.com/quest=13878/through-fire-and-flames"

**Comment by GMTyrial** [comment] 2015-12-11 18:59
Duplicate of https://github.com/HellscreamWoW/Tracker/issues/1074

**Closed by GMTyrial** 2015-12-11 18:59 UTC
Labels: Priority-Normal, Type-Item, Type-Quest
