### ISSUE TITLE
Quest "The Battle of Thandol Span" - Thandol Span - Wetlands

### ISSUE THREAD

**Issue by Kalae** [HellscreamWoW/Tracker#1809] opened 2015-08-09 10:55 UTC
http://www.wowhead.com/quest=26128/the-battle-of-thandol-span

No NPCs. Not working.

**Comment by GMTyrial** [comment] 2015-12-09 23:41
Duplicate of https://github.com/HellscreamWoW/Tracker/issues/2159

**Closed by GMTyrial** 2015-12-09 23:41 UTC
Labels: Type-Creature, Type-Quest, Type-Spawn
