### ISSUE TITLE
Quest "Feeding the Hungry and the Hopeless" not working

### ISSUE THREAD

**Issue by tribaljet** [HellscreamWoW/Tracker#1424] opened 2015-07-22 18:10 UTC
When setting down Westfall Stew, the requires NPCs do not move towards the item and there is no quest objective progress either.

**Comment by GMTyrial** [comment] 2015-12-07 17:09
Duplicate of https://github.com/HellscreamWoW/Tracker/issues/184

**Closed by GMTyrial** 2015-12-07 17:09 UTC
Labels: Type-Creature, Type-Gossip, Type-Quest, Type-Script
