### ISSUE TITLE
Summit of Fate

### ISSUE THREAD

**Issue by GeneralCaveman** [HellscreamWoW/Tracker#1314] opened 2015-07-13 12:12 UTC
www.wowhead.com/quest=26517/summit-of-fate

You can't seem to loot the idols from the bodies.

**Comment by GeneralCaveman** [comment] 2015-07-13 12:14
https://github.com/HellscreamWoW/Tracker/issues/761 Duplicate of this issue

**Comment by GMTyrial** [comment] 2015-12-20 06:56
Duplicate of https://github.com/HellscreamWoW/Tracker/issues/762

**Closed by GMTyrial** 2015-12-20 06:56 UTC
Labels: Type-Loot, Type-Quest
