### ISSUE TITLE
[Quest] Proving Pit

### ISSUE THREAD

**Issue by Max-Hellscream** [HellscreamWoW/Tracker#513] opened 2015-05-22 06:05 UTC
"http://www.wowhead.com/quest=24642/proving-pit

Can't complete quest beacause when i come to NPC i should talk to (http://www.wowhead.com/npc=39062) there's missing option to say him something.. so Naga won't come out of cage."

**Comment by GMTyrial** [comment] 2015-12-10 21:05
Duplicate of https://github.com/HellscreamWoW/Tracker/issues/981

**Closed by GMTyrial** 2015-12-10 21:05 UTC
Labels: Priority-Normal, Type-Quest
