### ISSUE TITLE
Quest Through Fire and Flames

### ISSUE THREAD

**Issue by Eluniver** [HellscreamWoW/Tracker#3212] opened 2015-10-26 00:33 UTC
The quest is obtainable from Dorak - an orc NPC in the Northern Barrens. The wolves that are supposed to be freed can't be interacted, and using the poles does nothing for the completion of the quest. Sorry if this seems like a waste of time, I'm just trying to help locating the bugged quests!

**Comment by Guybrush-Hellscream** [comment] 2015-10-26 06:39
http://www.wowhead.com/quest=13878/through-fire-and-flames

**Comment by GMTyrial** [comment] 2015-12-11 18:58
Duplicate of https://github.com/HellscreamWoW/Tracker/issues/1074

**Closed by GMTyrial** 2015-12-11 18:58 UTC
Labels: Type-Creature, Type-Quest, Type-Script
