### ISSUE TITLE
Loch Modan - NPC - Torren Squarejaw

### ISSUE THREAD

**Issue by Guybrush-Hellscream** [HellscreamWoW/Tracker#2149] opened 2015-08-24 01:01 UTC
Name : Torren Squarejaw
Link Wowhead : http://www.wowhead.com/npc=1153/torren-squarejaw
 
Side : Alliance
Job : Explorer's League

What's wrong : This NPC always have a yellow question mark like you can return a quest. Fact is, even after returning every Explorer's League Document (6 of them http://www.wowhead.com/search?q=explorer%27s+league+document), it still stays. The trouble might lie in the last quest that he should give you after finishing returning every Explorer's League Document. This quest is "Heartfelt Appreciation" (http://www.wowhead.com/quest=13661/heartfelt-appreciation) and he doesn't give it.

Screenshot IG : 
![loch modan - 1](https://cloud.githubusercontent.com/assets/13908354/9431178/81adb3da-4a0c-11e5-912b-972ee23e0962.PNG)

**Comment by GMTyrial** [comment] 2015-12-07 17:31
Duplicate of https://github.com/HellscreamWoW/Tracker/issues/2707

**Closed by GMTyrial** 2015-12-07 17:31 UTC
Labels: Type-Creature, Type-Script
