### ISSUE TITLE
[Quest] The Zhevra

### ISSUE THREAD

**Issue by Malae1** [HellscreamWoW/Tracker#2531] opened 2015-09-15 23:23 UTC
[The Zhevra](http://www.wowhead.com/quest=845)

The creatures "[Zhevra Runner](http://www.wowhead.com/npc=3242/zhevra-runner)" are invalid targets and are laying on the ground like they are dead.

![Zhevra](http://i.imgur.com/gZZoorC.png)

**Comment by BraynStorm** [comment] 2015-09-16 15:08
Duplicate of #1092?

**Closed** 2015-12-09 01:32 UTC
Labels: Type-Creature, Type-Quest, Type-Script
