### ISSUE TITLE
Murder Was The Case That They Gave Me

### ISSUE THREAD

**Issue by samvel2804** [HellscreamWoW/Tracker#3635] opened 2015-11-17 08:10 UTC
During the quest "Murder Was The Case That They Gave Me" in westfall i need to talk to hobos but the options for the conversation are missing so i cant talk to them.
http://www.wowhead.com/quest=26209/murder-was-the-case-that-they-gave-me
And the followup quests are available from the start without requaering this one to be complete

**Comment by samvel2804** [comment] 2015-11-17 08:14
someone else already made a report of this so im closing this one

**Comment by GMTyrial** [comment] 2015-12-07 17:16
Duplicate of https://github.com/HellscreamWoW/Tracker/issues/2940

**Closed by GMTyrial** 2015-12-07 17:16 UTC
Labels: Type-Creature, Type-Gossip, Type-Quest, Type-Script
