### ISSUE TITLE
Quest -  [Feeling Crabby?]

### ISSUE THREAD

**Issue by baalvi** [HellscreamWoW/Tracker#2026] opened 2015-08-17 21:39 UTC
hi quest  [Feeling Crabby?] http://www.wowhead.com/quest=26177/feeling-crabby no work q, no cant collect and nothing attack :(

**Comment by GMTyrial** [comment] 2015-12-07 20:31
Duplicate of https://github.com/HellscreamWoW/Tracker/issues/1970

**Closed by GMTyrial** 2015-12-07 20:31 UTC
Labels: Type-Creature, Type-Object, Type-Quest
