### ISSUE TITLE
Chaos Bolt bug

### ISSUE THREAD

**Issue by Burag** [HellscreamWoW/Tracker#1513] opened 2015-07-27 10:16 UTC
Link to the spell: http://www.wowhead.com/spell=116858/chaos-bolt
It says "always a critical hit" but it doesn't do a critical dmg at all.

**Comment by GMTyrial** [comment] 2015-12-07 21:52
Duplicate of https://github.com/HellscreamWoW/Tracker/issues/3197

**Closed by GMTyrial** 2015-12-07 21:52 UTC
Labels: Class-Warlock, Type-Spell
