### ISSUE TITLE
[Quest] [Ashenvale] : He who would be forgotten

### ISSUE THREAD

**Issue by K-Reeboo** [HellscreamWoW/Tracker#3858] opened 2015-12-08 10:53 UTC
Missing NPC at location to return quest.
He should be near the moon well at Raynwood Tower.

http://www.wowhead.com/quest=13921/he-who-would-be-forgiven

**Comment by GMTyrial** [comment] 2015-12-11 23:35
Duplicate of https://github.com/HellscreamWoW/Tracker/issues/3349

**Closed by GMTyrial** 2015-12-11 23:35 UTC
Labels: Type-Creature, Type-Quest, Type-Spawn
