### ISSUE TITLE
Axis of Awful (Quest)

### ISSUE THREAD

**Issue by emil494** [HellscreamWoW/Tracker#2744] opened 2015-10-04 12:39 UTC
Cannary's Cache dosnt give you the items it should. It should give you: Clever Plant Disguise Kit and Potent Murloc Pheromones.
Cannary's Cache: http://www.wowhead.com/item=60681/cannarys-cache
Quest: http://www.wowhead.com/quest=26868/axis-of-awful

**Comment by capcrowley** [comment] 2015-10-06 01:21
I killed the mosshide and he dropped the items however i couldnt use the murloc pheramones on him and would always do it on myself

**Comment by GMTyrial** [comment] 2015-12-07 17:30
Duplicate of https://github.com/HellscreamWoW/Tracker/issues/2148

**Closed by GMTyrial** 2015-12-07 17:30 UTC
Labels: Type-Item, Type-Quest, Type-Script
