### ISSUE TITLE
Argent Call: The Trial of the Crypt

### ISSUE THREAD

**Issue by GeneralCaveman** [HellscreamWoW/Tracker#1501] opened 2015-07-27 02:16 UTC
http://www.wowhead.com/quest=27464/argent-call-the-trial-of-the-crypt

This gives the error of being in the wrong location when using the scroll.

**Comment by GMTyrial** [comment] 2015-12-20 01:39
Duplicate of https://github.com/HellscreamWoW/Tracker/issues/998

**Closed by GMTyrial** 2015-12-20 01:39 UTC
Labels: Type-Item, Type-Quest, Type-Script
