### ISSUE TITLE
Quest "Winterfall Activity" quest items drop rate bug

### ISSUE THREAD

**Issue by tribaljet** [HellscreamWoW/Tracker#1559] opened 2015-07-29 20:37 UTC
Considering the Winterfall Spirit Beads quest item has a 43-54% drop rate and having farmed for a long time without any quest items dropping, nor the proper NPCs having any mention of belonging to the quest, this can be an issue.

**Comment by Guybrush-Hellscream** [comment] 2015-09-01 12:33
Confirmed, either really low drop rate (less than 1%) or they don't drop it.

**Comment by Klickeazy** [comment] 2015-11-22 04:35
I think the drop hasn't been added because the units might highlight with the quest tracker as possible units that drop the quest item. As of this post, still no drop after cleaning out the camp a few times.

**Comment by Malae1** [comment] 2015-11-24 13:53
Fixed in next update

**Closed by Malae1** 2015-11-24 13:53 UTC
Labels: Type-Loot, Type-Quest
