### ISSUE TITLE
Quest: Frost Nova in Sunstrider Isle

### ISSUE THREAD

**Issue by loefflefarn93** [HellscreamWoW/Tracker#2982] opened 2015-10-15 19:58 UTC
Link: http://www.wowhead.com/quest=10068/frost-nova

In the task execution of the spell is not recognized.

**Comment by GMTyrial** [comment] 2015-12-10 19:31
Duplicate of https://github.com/HellscreamWoW/Tracker/issues/887

**Closed by GMTyrial** 2015-12-10 19:31 UTC
Labels: Type-Quest, Type-Script, Type-Spell

**Comment by Pure-Valhalla** [comment] 2016-02-13 03:41
#4621 - combined all the class specific quests for this area together
