### ISSUE TITLE
The Embalmer's Revenge - Boss Missing

### ISSUE THREAD

**Issue by Dracoknight256** [HellscreamWoW/Tracker#1234] opened 2015-07-02 12:26 UTC
http://www.wowhead.com/quest=26727/the-embalmers-revenge

Stitches doesn't spawn

**Comment by GMTyrial** [comment] 2015-12-07 17:37
Duplicate of https://github.com/HellscreamWoW/Tracker/issues/831

**Closed by GMTyrial** 2015-12-07 17:37 UTC
Labels: Type-Creature, Type-Quest, Type-Script, Type-Spawn
