### ISSUE TITLE
Further Concerns

### ISSUE THREAD

**Issue by samvel2804** [HellscreamWoW/Tracker#3605] opened 2015-11-16 08:07 UTC
in the quest "Further Concerns" the starting NPC "Marshal Dughan" offerst a charger (temporary mount that the player can't control but only ride it on the path to Guard Thomas) it says "Let me know if you wish to make use of the horse." but it never offers it wen we speak to him again.
http://www.wowhead.com/quest=35/further-concerns

**Comment by GMTyrial** [comment] 2015-12-07 17:06
Duplicate of https://github.com/HellscreamWoW/Tracker/issues/2583

**Closed by GMTyrial** 2015-12-07 17:06 UTC
Labels: Type-Creature, Type-Gossip, Type-Quest
